### ISSUE TITLE
ImportError: Bio.Alphabet has been removed from Biopython.

### ISSUE THREAD

**Issue by morgansobol** [DavidBSauer/OGT_prediction#7]
Hi again David,

It looks like newer versions of BioPython are not compatible with your script. I will try to convert to an older version on my HPC but I just wanted to give you a heads up. Or do you already have a solution for this?

`Traceback (most recent call last):
  File "/home/kit/ibg/fh9393/bin/OGT_prediction/prediction/prediction_pipeline.py", line 12, in <module>
    import genome_analysis
  File "/pfs/data5/home/kit/ibg/fh9393/bin/OGT_prediction/prediction/genome_analysis.py", line 10, in <module>
    import external_tools
  File "/pfs/data5/home/kit/ibg/fh9393/bin/OGT_prediction/prediction/external_tools.py", line 4, in <module>
    from Bio.Alphabet import generic_rna, generic_dna
  File "/home/kit/ibg/fh9393/.local/lib/python3.10/site-packages/Bio/Alphabet/__init__.py", line 20, in <module>
    raise ImportError(
ImportError: Bio.Alphabet has been removed from Biopython. In many cases, the alphabet can simply be ignored and removed from scripts. In a few cases, you may need to specify the ``molecule_type`` as an annotation on a SeqRecord for your script to work correctly. Please see https://biopython.org/wiki/Alphabet for more information.`

Best,
Morgan

**Comment by DavidBSauer** [comment]
Hi Morgan,
Thank you for flagging this. I have updated the scripts to no longer specify the alphabet. 

Good luck!

Best,
David
